// This file is auto-generated by wasm-pack.
// Run `wasm-pack build --target bundler` in crates/string-width/ to regenerate.
// Before the WASM build, this module provides a no-op shim.

export function string_width_wasm(_s: string): number {
  return 0
}
